import fs from "node:fs"; import path from "node:path"; import crypto from "node:crypto"; import { fileURLToPath } from "node:url";
import { canonicalRoot, parseOptions, readJson, writeJsonAtomic } from "./full-lifecycle-lib.mjs";
import { proposedProfileIds } from "./design-lib.mjs";
export function resolveProfiles(repoRoot, selected) {
 const registry=readJson(path.join(repoRoot,"harness/profiles/registry.json")); const byId=new Map();
 for(const entry of registry.profiles){ if(byId.has(entry.id)) throw new Error(`Duplicate profile id: ${entry.id}`); const profile=readJson(path.join(repoRoot,entry.path)); if(profile.id!==entry.id) throw new Error(`Profile identity mismatch: ${entry.id}`); byId.set(entry.id,{...profile,path:entry.path}); }
 const resolved=[]; const visiting=new Set(); const visited=new Set();
 function visit(id){ if(visiting.has(id)) throw new Error(`Profile dependency cycle at ${id}`); if(visited.has(id)) return; const profile=byId.get(id); if(!profile) throw new Error(`Unknown profile: ${id}`); visiting.add(id); for(const req of profile.requires) visit(req); visiting.delete(id); visited.add(id); resolved.push(id); }
 for(const id of selected) visit(id);
 const set=new Set(resolved); for(const id of resolved){ for(const conflict of byId.get(id).conflicts) if(set.has(conflict)) throw new Error(`Profile conflict: ${id} conflicts with ${conflict}`); }
 const commands={}; const checks=[]; const capabilities=[]; const riskControls=[];
 for(const id of resolved){ const p=byId.get(id); for(const [name,command] of Object.entries(p.commands)){ if(commands[name] && commands[name]!==command) throw new Error(`Command conflict for ${name}`); commands[name]=command; } checks.push(...p.checks); capabilities.push(...p.capabilities); riskControls.push(...p.riskControls); }
 return {schemaVersion:"1.0.0",status:"resolved",requestedProfiles:[...new Set(selected)],resolvedProfiles:resolved,commands,checks:[...new Set(checks)],capabilities:[...new Set(capabilities)],riskControls:[...new Set(riskControls)]};
}
if(process.argv[1] && path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){ const options=parseOptions(process.argv.slice(2)); const projectPath=path.join(canonicalRoot,"harness/project.json"); const project=readJson(projectPath); const selected=(options.profiles?options.profiles.split(",").map(x=>x.trim()).filter(Boolean):proposedProfileIds(project)); if(!selected.length) throw new Error("No profiles selected. Pass --profiles id,id or define proposed/active profiles."); const resolution=resolveProfiles(canonicalRoot,selected); const registryBytes=fs.readFileSync(path.join(canonicalRoot,"harness/profiles/registry.json")); resolution.registrySha256=crypto.createHash("sha256").update(registryBytes).digest("hex"); const output="harness/generated/profile-resolution.json"; const outputPath=path.join(canonicalRoot,output); let generatedAt=new Date().toISOString(); if(fs.existsSync(outputPath)){ try{ const previous=readJson(outputPath); const previousComparable={...previous}; delete previousComparable.generatedAt; if(JSON.stringify(previousComparable)===JSON.stringify(resolution)) generatedAt=previous.generatedAt; }catch{} } resolution.generatedAt=generatedAt; writeJsonAtomic(outputPath,resolution); project.profileResolutionPath=output; writeJsonAtomic(projectPath,project); console.log(JSON.stringify(resolution,null,2)); }
