import crypto from "node:crypto"; import fs from "node:fs"; import path from "node:path";
import { appendHistory, canonicalRoot, parseOptions, readJson, sha256Files, transitionFor, writeJsonAtomic } from "./full-lifecycle-lib.mjs";
const options=parseOptions(process.argv.slice(2)); if(!options.to) throw new Error("Usage: project:advance -- --to <STATE>");
const file=path.join(canonicalRoot,"harness/project.json"); const project=readJson(file); const transition=transitionFor(canonicalRoot,"project",project.state,options.to); const approval=project.pendingApproval;
if(transition.approval==="human" && (!approval || approval.targetState!==options.to)) throw new Error(`Missing human approval for ${project.state} -> ${options.to}.`);
const digest=sha256Files(canonicalRoot,transition.requiredDocuments); if(approval && digest!==approval.contractHash) throw new Error("Approved project contract changed after approval.");
if(options.to==="ACTIVE") { if(!project.projectId || project.projectId==="change-me") throw new Error("ACTIVE requires a real projectId (replace bootstrap value change-me)."); if(!project.profileResolutionPath) throw new Error("ACTIVE requires a recorded profile resolution."); const resolution=readJson(path.join(canonicalRoot,project.profileResolutionPath)); if(resolution.status!=="resolved") throw new Error("Profile resolution is not resolved."); const registryDigest=crypto.createHash("sha256").update(fs.readFileSync(path.join(canonicalRoot,"harness/profiles/registry.json"))).digest("hex"); if(resolution.registrySha256!==registryDigest) throw new Error("Profile resolution is stale; run profile:resolve again."); const expected=project.migration?.proposedProfiles ?? project.activeProfiles; if(expected.length && expected.some((id)=>!resolution.resolvedProfiles.includes(id))) throw new Error("Profile resolution does not cover the approved profile candidates."); project.activeProfiles=resolution.resolvedProfiles; }
const from=project.state; const actor=approval?.approvedBy ?? "system"; const reason=approval?.reason ?? "deterministic transition"; appendHistory(project,from,options.to,actor,reason,digest); project.state=options.to; project.pendingApproval=null; if(options.to==="ACTIVE") project.migration=null; writeJsonAtomic(file,project);
console.log(JSON.stringify({from,state:project.state,activeProfiles:project.activeProfiles},null,2));
