import path from "node:path";
import { appendHistory, assertNoLikelySecret, canonicalRoot, parseOptions, readJson, requireHuman, safeId, transitionFor, writeJsonAtomic } from "./full-lifecycle-lib.mjs";
const o=parseOptions(process.argv.slice(2)); const id=safeId(o.id,/^REL-\d{4}-\d{2}-\d{2}-[a-z0-9-]+$/,"release id"); if(!o.to||!o.actor||!o.reason) throw new Error("--to, --actor, and --reason are required."); assertNoLikelySecret(JSON.stringify(o)); const file=path.join(canonicalRoot,"docs/operations/releases",id,"gate.json"); const r=readJson(file); const t=transitionFor(canonicalRoot,"release",r.state,o.to); if(t.approval==="human") requireHuman(o.actor);
if(o.to==="PREVIEW_VERIFIED"){ if(!o.url||!o.evidence) throw new Error("Preview verification requires --url and --evidence."); r.preview={status:"passed",url:o.url,evidence:o.evidence,recordedAt:new Date().toISOString()}; }
if(o.to==="PRODUCTION_APPROVED"){ requireHuman(o.actor); r.productionApproval={status:"approved",approvedBy:o.actor,approvedAt:new Date().toISOString(),reason:o.reason}; }
if(o.to==="DEPLOYED"){ requireHuman(o.actor); if(r.productionApproval.status!=="approved") throw new Error("Production approval is missing."); if(!o.deployment||!o.environment||!o.rollback) throw new Error("Deployment recording requires --deployment, --environment, and --rollback."); r.deployment={deploymentId:o.deployment,environment:o.environment,commitSha:r.artifact.commitSha,recordedBy:o.actor,recordedAt:new Date().toISOString(),rollbackTarget:o.rollback}; }
if(o.to==="OBSERVING") r.observation={status:"pending",summary:null,evidence:[],recordedAt:new Date().toISOString()};
if(o.to==="ACCEPTED"){ requireHuman(o.actor); if(!o.summary) throw new Error("Acceptance requires --summary."); r.observation={status:"healthy",summary:o.summary,evidence:o.evidence?[o.evidence]:[],recordedAt:new Date().toISOString()}; }
appendHistory(r,r.state,o.to,o.actor,o.reason); r.state=o.to; writeJsonAtomic(file,r); console.log(JSON.stringify({releaseId:id,state:r.state},null,2));
